name: pinecone-assistant
services:
  - name: web
    instance_type: nano
    build:
      builder: python
    ports:
      - port: 8080
    env:
      - name: PINECONE_API_KEY
        value: PINECONE_API_KEY
      - name: ASSISTANT_NAME
        value: ASSISTANT_NAME
    healthcheck:
      port: 8080
      path: /health
      initial_delay: 10s