name: pinecone-assistant
services:
  - name: web
    instance_type: nano
    build:
      builder: python
    ports:
      - port: 8080
    env:
      - name: PINECONE_API_KEY
        value: pcsk_7Pqpvr_AzKRnajNm47FRJgzMBsHfCDVnYQ42VvqBrb1DxzWHfScbMVaPoVTyXEQPbCmWHF
      - name: ASSISTANT_NAME
        value: testing-pdf-data
    healthcheck:
      port: 8080
      path: /health
      initial_delay: 10s